Repository TeamShortWeather/ShortWeather-AOS, pull requests merged in 2023-01, with the labels that each got.

#9 [ui] 설정 화면 구현
  app/src/main/java/org/shortweather/presentation/setting/view/SettingFragment.kt
  app/src/main/res/drawable/ic_next_btn.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/strings.xml
Labels: ui, 아라 🐋

#12 [ui] 주간 날씨 화면 구현
  app/src/main/java/org/shortweather/presentation/weeklyweather/WeeklyWeatherFragment.kt
  app/src/main/res/drawable/ic_weekly_weather_example.xml
  app/src/main/res/layout/fragment_weekly_weather.xml
  app/src/main/res/layout/item_weekly_weather.xml
  app/src/main/res/layout/item_weekly_weather_header.xml
  app/src/main/res/values/strings.xml
Labels: ui, 아라 🐋, done

#14 [ui] 오늘 날씨 UI 구현
  app/build.gradle
  app/src/main/java/org/shortweather/presentation/MainActivity.kt
  app/src/main/java/org/shortweather/presentation/customweather/view/CustomWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweather/view/TodayWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweathercontainer/adapter/TodayWeatherContainerAdapter.kt
  app/src/main/java/org/shortweather/presentation/todayweathercontainer/view/TodayWeatherContainerFragment.kt
  app/src/main/res/drawable/bg_blue_circle.xml
  app/src/main/res/drawable/bg_day.xml
  app/src/main/res/drawable/bg_gray_circle.xml
  app/src/main/res/drawable/bg_today_weather_description.xml
  app/src/main/res/drawable/ic_expand_down.xml
  app/src/main/res/drawable/ic_toast.xml
  app/src/main/res/drawable/img_lightning.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_custom_weather.xml
  app/src/main/res/layout/fragment_today_weather.xml
  app/src/main/res/layout/fragment_today_weather_container.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: ui, 선웅 🐬

#16 [style] text appearance & color 추가
  app/src/main/res/layout/activity_input_info.xml
  app/src/main/res/layout/activity_input_time.xml
  app/src/main/res/layout/fragment_custom_weather.xml
  app/src/main/res/layout/fragment_today_weather.xml
  app/src/main/res/layout/item_weekly_weather.xml
  app/src/main/res/layout/item_weekly_weather_header.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: style, 선웅 🐬

#19 [ui] 오늘 날씨 & 맞춤 날씨 UI text appearance 수정
  app/src/main/res/layout/fragment_custom_weather.xml
  app/src/main/res/layout/fragment_today_weather.xml
Labels: ui, 선웅 🐬

#17 [feat] 주간 날씨 화면 어댑터 구현
  app/src/main/java/org/shortweather/data/source/remote/ResponseWeeklyWeather.kt
  app/src/main/java/org/shortweather/presentation/weeklyweather/adapter/WeeklyWeatherAdapter.kt
  app/src/main/java/org/shortweather/presentation/weeklyweather/view/WeeklyWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/weeklyweather/viewmodel/WeeklyWeatherViewModel.kt
  app/src/main/res/layout/fragment_today_weather.xml
  app/src/main/res/layout/fragment_weekly_weather.xml
  app/src/main/res/layout/item_weekly_weather.xml
  app/src/main/res/layout/item_weekly_weather_header.xml
Labels: feat, 아라 🐋, done

#22 [ui] 주간 날씨 화면 추가 수정
  app/src/main/res/layout/fragment_weekly_weather.xml
  app/src/main/res/layout/item_weekly_weather.xml
  app/src/main/res/layout/item_weekly_weather_header.xml
Labels: ui, 아라 🐋, done

#24 [feat] 정보입력폼 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/shortweather/presentation/input/BottomSheetAdapter.kt
  app/src/main/java/org/shortweather/presentation/input/adapter/BottomSheetAdapter.kt
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetTimeFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputInfoActivity.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputInfoViewModel.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputTimeViewModel.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/java/org/shortweather/presentation/todayweather/TodayWeatherFragment.kt
  app/src/main/res/drawable/bg_bottom_sheet_btn_blue.xml
  app/src/main/res/drawable/bg_bottom_sheet_btn_gray.xml
  app/src/main/res/drawable/ic_bottom_sheet_drag_view.xml
  app/src/main/res/drawable/ic_expand_red.xml
  app/src/main/res/drawable/selector_input_btn_bg.xml
  app/src/main/res/drawable/selector_input_btn_text_color.xml
  app/src/main/res/layout/activity_input_info.xml
  app/src/main/res/layout/activity_input_time.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/bottom_sheet_age_content.xml
  app/src/main/res/layout/bottom_sheet_content.xml
  app/src/main/res/layout/bottom_sheet_gender_content.xml
  app/src/main/res/layout/bottom_sheet_sense_content.xml
  app/src/main/res/layout/bottom_sheet_time_content.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feat, 승운 🐳

#28 [ui] 시간 설정 화면 구현
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetFragment.kt
  app/src/main/java/org/shortweather/presentation/setting/view/OtherTimeSettingActivity.kt
  app/src/main/java/org/shortweather/presentation/setting/view/WakeTimeSettingActivity.kt
  app/src/main/res/layout/activity_other_time_setting.xml
  app/src/main/res/layout/activity_wake_time_setting.xml
  app/src/main/res/values/strings.xml
Labels: ui, 승운 🐳

#29 [ui] 알림 설정 화면 구현
  app/build.gradle
  app/src/main/java/org/shortweather/presentation/alarmsetting/view/AlarmSettingActivity.kt
  app/src/main/java/org/shortweather/presentation/weeklyweather/WeeklyWeatherFragment.kt
  app/src/main/res/layout/activity_alarm_setting.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: ui, 아라 🐋, done

#33 [feat] 알림 설정 화면 기능 구현
  app/src/main/java/org/shortweather/presentation/alarmsetting/view/AlarmSettingActivity.kt
  app/src/main/java/org/shortweather/presentation/alarmsetting/viewmodel/AlarmSettingViewModel.kt
  app/src/main/res/layout/activity_alarm_setting.xml
Labels: feat, 아라 🐋, done

#34 [ui] 주간 날씨 화면 ui 수정
  app/src/main/java/org/shortweather/presentation/alarmsetting/view/AlarmSettingActivity.kt
  app/src/main/java/org/shortweather/presentation/alarmsetting/viewmodel/AlarmSettingViewModel.kt
  app/src/main/res/layout/item_weekly_weather_header.xml
Labels: feat, 아라 🐋, done

#35 [feat] 시간 설정 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetTimeFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputInfoActivity.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputTimeViewModel.kt
  app/src/main/java/org/shortweather/presentation/setting/view/OtherTimeSettingActivity.kt
  app/src/main/java/org/shortweather/presentation/setting/view/WakeTimeSettingActivity.kt
  app/src/main/res/layout/activity_other_time_setting.xml
  app/src/main/res/layout/activity_wake_time_setting.xml
Labels: feat, 승운 🐳

#37 [ui] 맞춤 날씨 UI 추가 구현
  app/src/main/java/org/shortweather/data/model/CustomWeather.kt
  app/src/main/java/org/shortweather/presentation/customweather/adapter/CustomWeatherPrecipitationAdapter.kt
  app/src/main/java/org/shortweather/presentation/customweather/adapter/CustomWeatherWeatherAdapter.kt
  app/src/main/java/org/shortweather/presentation/customweather/view/CustomWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/customweather/viewmodel/CustomWeatherViewModel.kt
  app/src/main/java/org/shortweather/presentation/todayweather/TodayWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweather/view/TodayWeatherFragment.kt
  app/src/main/java/org/shortweather/util/Constants.kt
  app/src/main/res/layout/fragment_custom_weather.xml
  app/src/main/res/layout/fragment_today_weather.xml
  app/src/main/res/layout/item_custom_weather_precipitation.xml
  app/src/main/res/layout/item_custom_weather_weather.xml
Labels: ui, feat, 선웅 🐬

#38 [ui] 정보입력폼 뷰 수정
  app/src/main/res/layout/activity_input_info.xml
  app/src/main/res/layout/activity_input_time.xml
Labels: ui, 승운 🐳

#40 [style] 리소스 추출
  app/src/main/res/drawable/bg_cloud.xml
  app/src/main/res/drawable/bg_fog.xml
  app/src/main/res/drawable/bg_night.xml
  app/src/main/res/drawable/bg_rain.xml
  app/src/main/res/drawable/bg_snow.xml
  app/src/main/res/drawable/bg_windy.xml
  app/src/main/res/drawable/bg_yellowdust.xml
  app/src/main/res/drawable/ic_clear_day.xml
  app/src/main/res/drawable/ic_clear_night.xml
  app/src/main/res/drawable/ic_cloudy.xml
  app/src/main/res/drawable/ic_dust_bad.xml
  app/src/main/res/drawable/ic_dust_good.xml
  app/src/main/res/drawable/ic_dust_normal.xml
  app/src/main/res/drawable/ic_dust_worst.xml
  app/src/main/res/drawable/ic_fog.xml
  app/src/main/res/drawable/ic_hail.xml
  app/src/main/res/drawable/ic_heavyrain.xml
  app/src/main/res/drawable/ic_heavysnow.xml
  app/src/main/res/drawable/ic_humidity.xml
  app/src/main/res/drawable/ic_lightning.xml
  app/src/main/res/drawable/ic_lightrain.xml
  app/src/main/res/drawable/ic_lightsnow.xml
  app/src/main/res/drawable/ic_littlecloud_day.xml
  app/src/main/res/drawable/ic_littlecloud_night.xml
  app/src/main/res/drawable/ic_lotcloud_day.xml
  app/src/main/res/drawable/ic_lotcloud_night.xml
  app/src/main/res/drawable/ic_precipitation_1.xml
  app/src/main/res/drawable/ic_precipitation_10.xml
  app/src/main/res/drawable/ic_precipitation_2.xml
  app/src/main/res/drawable/ic_precipitation_3.xml
  app/src/main/res/drawable/ic_precipitation_4.xml
  app/src/main/res/drawable/ic_precipitation_5.xml
  app/src/main/res/drawable/ic_precipitation_6.xml
  app/src/main/res/drawable/ic_precipitation_7.xml
  app/src/main/res/drawable/ic_precipitation_8.xml
  app/src/main/res/drawable/ic_precipitation_9.xml
  app/src/main/res/drawable/ic_rain.xml
  app/src/main/res/drawable/ic_rainsnow.xml
  app/src/main/res/drawable/ic_shower.xml
  app/src/main/res/drawable/ic_snow.xml
  app/src/main/res/drawable/ic_sunrise.xml
  app/src/main/res/drawable/ic_sunset.xml
  app/src/main/res/drawable/ic_windy.xml
  app/src/main/res/drawable/ic_yellowdust.xml
Labels: style, 아라 🐋, done

#44 [feat] 디바이스 토큰 저장 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/shortweather/ShortWeatherApplication.kt
  app/src/main/java/org/shortweather/data/model/InfoInput.kt
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputInfoActivity.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputTimeViewModel.kt
  app/src/main/java/org/shortweather/presentation/setting/view/WakeTimeSettingActivity.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/java/org/shortweather/util/ShortWeatherFirebaseMessagingService.kt
  app/src/main/java/org/shortweather/util/ShortWeatherSharedPreference.kt
  app/src/main/res/layout/item_bottom_sheet.xml
  build.gradle
Labels: feat, 승운 🐳, done

#46 [ui] 오늘 날씨 -> 맞춤 날씨 중첩 스크롤 문제 해결
  app/src/main/java/org/shortweather/presentation/customweather/view/CustomWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweather/view/TodayWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweathercontainer/view/TodayWeatherContainerFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweathercontainer/viewmodel/TodayWeatherContainerViewModel.kt
  app/src/main/java/org/shortweather/util/NestedScrollableHost.kt
  app/src/main/res/layout/fragment_custom_weather.xml
  app/src/main/res/layout/fragment_today_weather_container.xml
Labels: ui, feat, 선웅 🐬

#48 [fix] 서버통신 대비 viewModel 개편
  app/src/main/java/org/shortweather/data/model/InfoInput.kt
  app/src/main/java/org/shortweather/data/model/SettingTimeData.kt
  app/src/main/java/org/shortweather/data/model/UserData.kt
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetTimeFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputInfoActivity.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputInfoViewModel.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputTimeViewModel.kt
  app/src/main/java/org/shortweather/presentation/setting/view/WakeTimeSettingActivity.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/java/org/shortweather/util/ShortWeatherSharedPreference.kt
  app/src/main/res/layout/activity_other_time_setting.xml
  app/src/main/res/layout/activity_wake_time_setting.xml
Labels: fix, 승운 🐳, done

#50 [ui] 오늘 날씨 Toast UI & 기능 구현
  app/src/main/java/org/shortweather/presentation/todayweather/view/TodayWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweather/viewmodel/TodayWeatherViewModel.kt
  app/src/main/res/drawable/bg_today_weather_toast.xml
  app/src/main/res/layout/fragment_today_weather.xml
Labels: ui, feat, 선웅 🐬

#52 [feat] 설정 화면 메뉴 기능 구현
  app/src/main/java/org/shortweather/presentation/setting/view/SettingFragment.kt
  app/src/main/res/drawable/ic_expand_right.xml
  app/src/main/res/layout/activity_alarm_setting.xml
  app/src/main/res/layout/fragment_setting.xml
Labels: feat, 아라 🐋, done

#54 [feat] 유저조회/정보입력 서버통신 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/shortweather/data/api/AuthService.kt
  app/src/main/java/org/shortweather/data/model/BaseResponse.kt
  app/src/main/java/org/shortweather/data/model/SettingTimeData.kt
  app/src/main/java/org/shortweather/data/model/UserData.kt
  app/src/main/java/org/shortweather/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/shortweather/data/source/remote/AuthRemoteDataSource.kt
  app/src/main/java/org/shortweather/di/NetworkModule.kt
  app/src/main/java/org/shortweather/di/RepositoryModule.kt
  app/src/main/java/org/shortweather/di/ServiceModule.kt
  app/src/main/java/org/shortweather/domain/repository/AuthRepository.kt
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetTimeFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputInfoViewModel.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputTimeViewModel.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/res/raw/shortweather_final.json
Labels: feat, 승운 🐳, done

#57 [feat] #56 액세스 토큰 저장 기능 구현
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputTimeViewModel.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/java/org/shortweather/util/ShortWeatherSharedPreference.kt
Labels: feat, 승운 🐳, done

#59 [refactor] 정보입력폼 코드 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/shortweather/ShortWeatherApplication.kt
  app/src/main/java/org/shortweather/presentation/input/adapter/BottomSheetAdapter.kt
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetTimeFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputInfoActivity.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputInfoViewModel.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputTimeViewModel.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/java/org/shortweather/util/ShortWeatherSharedPreference.kt
  app/src/main/res/layout/activity_input_time.xml
Labels: refactor, 승운 🐳

#60 [feat] 오늘 날씨 API 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/shortweather/data/api/TodayWeatherService.kt
  app/src/main/java/org/shortweather/data/model/TodayWeather.kt
  app/src/main/java/org/shortweather/data/repository/TodayWeatherRepositoryImpl.kt
  app/src/main/java/org/shortweather/data/source/remote/TodayWeatherRemoteDataSource.kt
  app/src/main/java/org/shortweather/di/RepositoryModule.kt
  app/src/main/java/org/shortweather/di/ServiceModule.kt
  app/src/main/java/org/shortweather/domain/repository/TodayWeatherRepository.kt
  app/src/main/java/org/shortweather/presentation/todayweather/adapter/TodayWeatherAdapter.kt
  app/src/main/java/org/shortweather/presentation/todayweather/view/TodayWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweather/viewmodel/TodayWeatherViewModel.kt
  app/src/main/java/org/shortweather/util/binding/BindingAdapter.kt
  app/src/main/res/layout/fragment_today_weather.xml
  app/src/main/res/layout/item_today_weather_fine_dust.xml
  app/src/main/res/layout/item_today_weather_ultrafine_dust.xml
Labels: ui, feat, 선웅 🐬

#64 [style] 앱 아이콘 적용
  app/src/main/AndroidManifest.xml
  app/src/main/res/mipmap-hdpi/ic_short_weather.png
  app/src/main/res/mipmap-mdpi/ic_short_weather.png
  app/src/main/res/mipmap-xhdpi/ic_short_weather.png
  app/src/main/res/mipmap-xxhdpi/ic_short_weather.png
  app/src/main/res/mipmap-xxxhdpi/ic_short_weather.png
Labels: style, 선웅 🐬

#65 [refactor] 뷰 중복클릭, 서버통신 예외처리
  app/src/main/java/org/shortweather/data/model/UserData.kt
  app/src/main/java/org/shortweather/presentation/input/adapter/BottomSheetAdapter.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputInfoActivity.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputTimeViewModel.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/java/org/shortweather/util/OnThrottleClickListener.kt
  app/src/main/java/org/shortweather/util/binding/BindingActivity.kt
  app/src/main/java/org/shortweather/util/extension/ViewExt.kt
  app/src/main/res/values/strings.xml
Labels: refactor, 승운 🐳

#69 [feat] 오늘 날씨 UI & 기능 완성
  app/src/main/java/org/shortweather/presentation/todayweather/view/TodayWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweather/viewmodel/TodayWeatherViewModel.kt
  app/src/main/java/org/shortweather/presentation/todayweathercontainer/OnPageDownClickListener.kt
  app/src/main/java/org/shortweather/presentation/todayweathercontainer/view/TodayWeatherContainerFragment.kt
  app/src/main/java/org/shortweather/util/binding/BindingAdapter.kt
  app/src/main/res/layout/fragment_today_weather.xml
  app/src/main/res/values/strings.xml
Labels: ui, feat, 선웅 🐬

#71 [fix] 서버통신 상태별 로직 수정
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputTimeViewModel.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/res/values/strings.xml
Labels: fix, 승운 🐳

#73 [feat] 오늘 날씨 시간대별 날씨 화면 기능 구현
  app/src/main/java/org/shortweather/data/api/CustomWeatherService.kt
  app/src/main/java/org/shortweather/data/model/CustomWeather.kt
  app/src/main/java/org/shortweather/data/repository/CustomWeatherRespositoryImpl.kt
  app/src/main/java/org/shortweather/data/source/remote/CustomWeatherDataSource.kt
  app/src/main/java/org/shortweather/di/RepositoryModule.kt
  app/src/main/java/org/shortweather/di/ServiceModule.kt
  app/src/main/java/org/shortweather/domain/repository/CustomWeatherRepository.kt
  app/src/main/java/org/shortweather/presentation/customweather/adapter/CustomWeatherPrecipitationAdapter.kt
  app/src/main/java/org/shortweather/presentation/customweather/adapter/CustomWeatherTempAdapter.kt
  app/src/main/java/org/shortweather/presentation/customweather/view/CustomWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/customweather/viewmodel/CustomWeatherViewModel.kt
  app/src/main/java/org/shortweather/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/ic_snowdrifting.xml
  app/src/main/res/drawable/img_lotcloud_day.png
  app/src/main/res/layout/fragment_custom_weather.xml
  app/src/main/res/layout/item_custom_weather_precipitation.xml
  app/src/main/res/layout/item_custom_weather_weather.xml
Labels: feat, 아라 🐋, done

#75 [fix] 일부 잘못된 로직 수정
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/input/viewmodel/InputTimeViewModel.kt
Labels: fix, 승운 🐳, done

#77 [feat] drawer layout navigation 기능 구현
  app/src/main/java/org/shortweather/presentation/MainActivity.kt
  app/src/main/java/org/shortweather/util/extension/ActivityExt.kt
  app/src/main/res/drawable/ic_hamberger_logo.xml
  app/src/main/res/drawable/ic_hamberger_text_logo.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/layout/item_drawer_header.xml
  app/src/main/res/menu/menu_drawer.xml
Labels: style, ui, feat, 선웅 🐬

#78 [feat] 맞춤 날씨 화면 API 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/shortweather/data/api/CustomWeatherService.kt
  app/src/main/java/org/shortweather/data/model/CustomWeather.kt
  app/src/main/java/org/shortweather/data/repository/CustomWeatherRespositoryImpl.kt
  app/src/main/java/org/shortweather/data/source/remote/CustomWeatherDataSource.kt
  app/src/main/java/org/shortweather/domain/repository/CustomWeatherRepository.kt
  app/src/main/java/org/shortweather/presentation/MainActivity.kt
  app/src/main/java/org/shortweather/presentation/customweather/view/CustomWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/customweather/viewmodel/CustomWeatherViewModel.kt
  app/src/main/java/org/shortweather/util/binding/BindingAdapter.kt
  app/src/main/res/layout/fragment_custom_weather.xml
Labels: feat, 아라 🐋, done

#80 [ui] 맞춤 날씨 화면 ui 수정
  app/src/main/java/org/shortweather/data/model/CustomWeather.kt
  app/src/main/res/layout/fragment_custom_weather.xml
Labels: ui, 아라 🐋, done

#82 [feat] #81 맞춤 날씨 화면 binding adapter 수정
  app/src/main/java/org/shortweather/util/binding/BindingAdapter.kt
Labels: feat, 아라 🐋, done

#84 [fix] 타임피커 키보드 접근 현상 수정
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/img_lotcloud_day.png
  app/src/main/res/layout/bottom_sheet_time_content.xml
Labels: fix, 승운 🐳, done

#86 [feat] 햄버거 위치 별 상단 이름 변경 및 설정 화면 location bar 비활성화
  app/src/main/java/org/shortweather/presentation/MainActivity.kt
  app/src/main/java/org/shortweather/presentation/MainViewModel.kt
  app/src/main/java/org/shortweather/presentation/customweather/view/CustomWeatherFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_drawer.xml
  app/src/main/res/values/strings.xml
Labels: ui, feat, 선웅 🐬

#88 [ui] 설정 UI 수정 & 설정 패키지 이동
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/shortweather/presentation/othertimesetting/view/OtherTimeSettingActivity.kt
  app/src/main/java/org/shortweather/presentation/setting/view/SettingFragment.kt
  app/src/main/java/org/shortweather/presentation/waketimesetting/view/WakeTimeSettingActivity.kt
  app/src/main/res/layout/activity_alarm_setting.xml
  app/src/main/res/layout/activity_other_time_setting.xml
  app/src/main/res/layout/activity_wake_time_setting.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/strings.xml
Labels: chore, ui, 선웅 🐬

#90 [chore] 가로 모드 제한
  app/src/main/AndroidManifest.xml
Labels: chore, 선웅 🐬

#91 [feat] 주간 날씨 화면 로직 수정
  app/src/main/java/org/shortweather/data/model/WeeklyWeather.kt
  app/src/main/java/org/shortweather/data/source/remote/ResponseWeeklyWeather.kt
  app/src/main/java/org/shortweather/presentation/weeklyweather/adapter/WeeklyWeatherAdapter.kt
  app/src/main/java/org/shortweather/presentation/weeklyweather/viewmodel/WeeklyWeatherViewModel.kt
  app/src/main/java/org/shortweather/util/binding/BindingAdapter.kt
  app/src/main/res/layout/item_weekly_weather.xml
Labels: feat, 아라 🐋, done

#93 [chore] #92 머지 오류 해결
  app/src/main/java/org/shortweather/util/binding/BindingAdapter.kt
Labels: chore, 아라 🐋, done

#97 [fix] SharedPreference 일부 잘못된 표현 수정
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/java/org/shortweather/util/ShortWeatherSharedPreference.kt
Labels: fix, 승운 🐳

#98 [feat] 오늘 날씨 조회 & 오늘 날씨 toast API 에러 처리
  app/src/main/java/org/shortweather/presentation/input/view/InputInfoActivity.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/java/org/shortweather/presentation/todayweather/view/TodayWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweather/viewmodel/TodayWeatherViewModel.kt
  app/src/main/java/org/shortweather/util/Constants.kt
Labels: feat, 선웅 🐬

#100 [feat] 맞춤 날씨 API 에러 처리
  app/src/main/java/org/shortweather/data/repository/CustomWeatherRepositoryImpl.kt
  app/src/main/java/org/shortweather/domain/repository/CustomWeatherRepository.kt
  app/src/main/java/org/shortweather/presentation/customweather/adapter/CustomWeatherTempAdapter.kt
  app/src/main/java/org/shortweather/presentation/customweather/view/CustomWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/customweather/viewmodel/CustomWeatherViewModel.kt
  app/src/main/java/org/shortweather/util/binding/BindingAdapter.kt
  app/src/main/res/layout/fragment_custom_weather.xml
Labels: ui, feat, refactor, 선웅 🐬

#102 [style] 에러 코드 텍스트 수정
  app/src/main/res/values/strings.xml
Labels: style, 선웅 🐬

#105 [feat] 주간 날씨 화면 더미데이터 삽입 및 수정
  app/src/main/java/org/shortweather/presentation/weeklyweather/adapter/WeeklyWeatherAdapter.kt
  app/src/main/java/org/shortweather/presentation/weeklyweather/viewmodel/WeeklyWeatherViewModel.kt
  app/src/main/java/org/shortweather/util/binding/BindingAdapter.kt
  app/src/main/res/layout/fragment_weekly_weather.xml
  app/src/main/res/layout/item_weekly_weather.xml
  app/src/main/res/layout/item_weekly_weather_header.xml
  app/src/main/res/values/strings.xml
Labels: feat, 아라 🐋, done

#104 [refactor] 오늘 날씨 & 맞춤 날씨 코드 리팩터링
  app/src/main/java/org/shortweather/presentation/customweather/viewmodel/CustomWeatherViewModel.kt
  app/src/main/java/org/shortweather/presentation/todayweather/viewmodel/TodayWeatherViewModel.kt
Labels: refactor, 선웅 🐬

#107 [feat] 설정 화면 버튼 영역 수정
  app/src/main/java/org/shortweather/presentation/setting/view/SettingFragment.kt
Labels: feat, 아라 🐋, done

#109 [fix] 주간 날씨 화면 color 수정
  app/src/main/java/org/shortweather/util/binding/BindingAdapter.kt
  app/src/main/res/layout/item_weekly_weather.xml
Labels: fix, 아라 🐋, done

#111 [feat] 사용성 기능 & 누락된 기능 추가
  app/src/main/java/org/shortweather/presentation/customweather/adapter/CustomWeatherPrecipitationAdapter.kt
  app/src/main/java/org/shortweather/presentation/todayweather/view/TodayWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweather/viewmodel/TodayWeatherViewModel.kt
  app/src/main/java/org/shortweather/presentation/weeklyweather/view/WeeklyWeatherFragment.kt
  app/src/main/res/layout/fragment_today_weather.xml
  app/src/main/res/layout/fragment_weekly_weather.xml
Labels: fix, ui, feat, 선웅 🐬

#113 [fix] 맞춤 날씨 data source 오타 수정
  app/src/main/java/org/shortweather/data/repository/CustomWeatherRepositoryImpl.kt
  app/src/main/java/org/shortweather/data/source/remote/CustomWeatherRemoteDataSource.kt
Labels: fix, 선웅 🐬, done

#115 [del] sample 클래스 제거 & 코드 리팩터링
  app/build.gradle
  app/src/main/java/org/shortweather/data/api/SampleService.kt
  app/src/main/java/org/shortweather/data/model/Sample.kt
  app/src/main/java/org/shortweather/data/repository/SampleRepositoryImpl.kt
  app/src/main/java/org/shortweather/data/source/remote/SampleRemoteDataSource.kt
  app/src/main/java/org/shortweather/di/RepositoryModule.kt
  app/src/main/java/org/shortweather/domain/repository/SampleRepository.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputInfoActivity.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/othertimesetting/view/OtherTimeSettingActivity.kt
  app/src/main/java/org/shortweather/presentation/sample/view/SampleActivity.kt
  app/src/main/java/org/shortweather/presentation/sample/viewmodel/SampleViewModel.kt
  app/src/main/java/org/shortweather/presentation/waketimesetting/view/WakeTimeSettingActivity.kt
  app/src/main/java/org/shortweather/util/extension/ViewExt.kt
  app/src/main/res/layout/activity_sample.xml
  build.gradle
Labels: del, refactor, 선웅 🐬

#117 [chore] 주요 string 상수화
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/BottomSheetTimeFragment.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputInfoActivity.kt
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
  app/src/main/java/org/shortweather/util/Constants.kt
Labels: chore, 승운 🐳, done

#119 [refactor] 오늘 날씨 & 맞춤 날씨 에러 분기 처리 코드 리팩터링
  app/src/main/java/org/shortweather/presentation/customweather/view/CustomWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/customweather/viewmodel/CustomWeatherViewModel.kt
  app/src/main/java/org/shortweather/presentation/todayweather/view/TodayWeatherFragment.kt
  app/src/main/java/org/shortweather/presentation/todayweather/viewmodel/TodayWeatherViewModel.kt
Labels: refactor, 선웅 🐬, done

#123 [ui] 주간 날씨 UI 수정
  app/src/main/java/org/shortweather/presentation/weeklyweather/adapter/WeeklyWeatherAdapter.kt
  app/src/main/java/org/shortweather/presentation/weeklyweather/view/WeeklyWeatherFragment.kt
  app/src/main/res/layout/fragment_weekly_weather.xml
  app/src/main/res/layout/item_weekly_weather.xml
Labels: ui, feat, refactor, 선웅 🐬

#122 [refactor] 실제 디바이스 토큰 로직으로 수정
  app/src/main/java/org/shortweather/presentation/input/view/InputTimeActivity.kt
  app/src/main/java/org/shortweather/presentation/splash/SplashActivity.kt
Labels: refactor, 승운 🐳

#128 [ui] 디자인 QA 반영 UI 수정
  app/src/main/res/drawable/bg_today_weather_sub_description.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_custom_weather.xml
  app/src/main/res/layout/fragment_today_weather.xml
  app/src/main/res/layout/fragment_weekly_weather.xml
Labels: ui, 선웅 🐬, done

#131 [fix] 일부 버그 수정
  app/src/main/java/org/shortweather/presentation/othertimesetting/view/OtherTimeSettingActivity.kt
  app/src/main/java/org/shortweather/presentation/waketimesetting/view/WakeTimeSettingActivity.kt
Labels: fix, 승운 🐳, done

#133 [fix] 시간설정 버그 수정
  app/src/main/java/org/shortweather/presentation/othertimesetting/view/OtherTimeSettingActivity.kt
Labels: fix, 승운 🐳
